#!/usr/bin/env python3
"""Lightweight offline backtest runner for trader signals.

This script loads a sample price series and simulates two simple policies:
- Momentum: go long when returns > 0, short otherwise
- Mean-revert: opposite of momentum
The goal is to demonstrate how tradable signals generated by the agent can be
validated offline, echoing the JD requirement for backtesting / A/B style flows.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import List


def load_prices(path: Path) -> List[float]:
    data = json.loads(path.read_text(encoding="utf-8"))
    return [float(x) for x in data.get("close", []) if x is not None]


def simulate(prices: List[float], reverse: bool = False) -> float:
    pnl = 0.0
    for i in range(1, len(prices)):
        ret = (prices[i] - prices[i - 1]) / prices[i - 1] if prices[i - 1] else 0.0
        signal = -1 if reverse else 1
        pnl += signal * ret
        reverse = ret > 0 if reverse else reverse
    return pnl * 100


def main() -> None:
    parser = argparse.ArgumentParser(description="Offline backtest demo")
    parser.add_argument("--data", default=Path(__file__).with_name("sample_backtest_data.json"), type=Path)
    args = parser.parse_args()
    prices = load_prices(args.data)
    momentum = simulate(prices)
    mean_revert = simulate(prices, reverse=True)
    print("Backtest complete on", len(prices), "sessions")
    print(f"Momentum PnL %: {momentum:.2f}")
    print(f"Mean Revert PnL %: {mean_revert:.2f}")


if __name__ == "__main__":
    main()
